### ISSUE TITLE
[BUG] Impossible to get a pool with filter that contains a subfilter with null value

### ISSUE THREAD

**Issue by Marishka17** [Toloka/toloka-kit#215]
### Observed behavior

If for some reason a pool contains a filter with null value (e.g. client.filter.DateOfBirth == None) then such pool cannot be received via `get_pool`. It is also a question of whether such filters should be allowed...

### Python Version

3.8

### Toloka-Kit Version

1.2.0.post1

### Example code

```Python
pool = toloka_client.get_pool(pool_id)
```

### Relevant log output

```shell
+ Exception Group Traceback (most recent call last):
  |   File "<stdin>", line 1, in <module>
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/util/_managing_headers.py", line 73, in wrapped
  |     return run_in_current_context(func, *args, **kwargs)
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/util/_managing_headers.py", line 100, in run_in_current_context
  |     result = func(*args, **kwargs)
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/__init__.py", line 1587, in get_pool
  |     >>> new_pool = toloka.client.Pool(
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 334, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/_converter.py", line 21, in <lambda>
  |     lambda type_: hasattr(type_, 'structure'),
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/primitives/base.py", line 317, in structure
  |     continue
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 334, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 646, in _structure_optional
  |     return self._structure_func.dispatch(other)(obj, other)
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/_converter.py", line 21, in <lambda>
  |     lambda type_: hasattr(type_, 'structure'),
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/filter.py", line 88, in structure
  |     return FilterAnd.structure(data)
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/filter.py", line 144, in structure
  |     return super(FilterCondition, cls).structure(data)
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/primitives/base.py", line 317, in structure
  |     continue
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 334, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 545, in _structure_list
  |     raise IterableValidationError(
  | cattrs.errors.IterableValidationError: While structuring typing.List[toloka.client.filter.FilterCondition] (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 535, in _structure_list
    |     res.append(handler(e, elem_type))
    |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/_converter.py", line 21, in <lambda>
    |     lambda type_: hasattr(type_, 'structure'),
    |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/filter.py", line 86, in structure
    |     return FilterOr.structure(data)
    |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/filter.py", line 117, in structure
    |     return super(FilterCondition, cls).structure(data)
    |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/primitives/base.py", line 317, in structure
    |     continue
    |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 334, in structure
    |     return self._structure_func.dispatch(cl)(obj, cl)
    |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 545, in _structure_list
    |     raise IterableValidationError(
    | cattrs.errors.IterableValidationError: While structuring typing.List[toloka.client.filter.FilterCondition] (1 sub-exception)
    | Structuring typing.List[toloka.client.filter.FilterCondition] @ index 0
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 535, in _structure_list
      |     res.append(handler(e, elem_type))
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/_converter.py", line 21, in <lambda>
      |     lambda type_: hasattr(type_, 'structure'),
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/filter.py", line 90, in structure
      |     return Condition.structure(data)
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/filter.py", line 175, in structure
      |     return super(FilterCondition, cls).structure(data)
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/primitives/base.py", line 305, in structure
      |     spec_class = cls._variant_registry.generate_subtype(cls, spec_value)
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/filter.py", line 175, in structure
      |     return super(FilterCondition, cls).structure(data)
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/primitives/base.py", line 305, in structure
      |     spec_class = cls._variant_registry.generate_subtype(cls, spec_value)
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/filter.py", line 175, in structure
      |     return super(FilterCondition, cls).structure(data)
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/toloka/client/primitives/base.py", line 317, in structure
      |     continue
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 334, in structure
      |     return self._structure_func.dispatch(cl)(obj, cl)
      |   File "/home/maya/Documents/cvat/env/lib/python3.8/site-packages/cattrs/converters.py", line 440, in _structure_call
      |     return cl(obj)
      | TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
      | Structuring typing.List[toloka.client.filter.FilterCondition] @ index 0
      +------------------------------------
```

**Comment by Pocoder** [comment]
Thank you for opening issue.
`client.filter.DateOfBirth.__init__`' `value` argument has type `int`, not `Optional[int]`.
We don't try to validate all possible incorrect inputs for now. Please, pay attention to type annotations.
