### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by saninstein** [Toloka/toloka-kit#244]
### Observed behavior

Raises exception
```
Traceback (most recent call last):
  File "/Users/alex/PycharmProjects/idface-toloka-dataflow/drafts/draft.py", line 44, in <module>
    cli.get_project('xxx')
  File "/Users/alex/PycharmProjects/idface-toloka-dataflow/venv/lib/python3.10/site-packages/toloka/util/_managing_headers.py", line 73, in wrapped
    return run_in_current_context(func, *args, **kwargs)
  File "/Users/alex/PycharmProjects/idface-toloka-dataflow/venv/lib/python3.10/site-packages/toloka/util/_managing_headers.py", line 100, in run_in_current_context
    result = func(*args, **kwargs)
  File "/Users/alex/PycharmProjects/idface-toloka-dataflow/venv/lib/python3.10/site-packages/toloka/client/__init__.py", line 1284, in get_project
    response = self._request('get', f'/v1/projects/{project_id}')
  File "/Users/alex/PycharmProjects/idface-toloka-dataflow/venv/lib/python3.10/site-packages/toloka/client/__init__.py", line 399, in _request
    return self._raw_request(method, path, **kwargs).json(parse_float=Decimal)
  File "/Users/alex/PycharmProjects/idface-toloka-dataflow/venv/lib/python3.10/site-packages/toloka/client/__init__.py", line 395, in _raw_request
    response = self._do_request_with_retries(method, f'/api{path}', **kwargs)
  File "/Users/alex/PycharmProjects/idface-toloka-dataflow/venv/lib/python3.10/site-packages/toloka/client/__init__.py", line 361, in _do_request_with_retries
    return wrapped(method, path, **kwargs)
  File "/Users/alex/PycharmProjects/idface-toloka-dataflow/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 334, in wrapped_f
    copy = self.copy()
  File "/Users/alex/PycharmProjects/idface-toloka-dataflow/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 260, in copy
    return self.__class__(
TypeError: RetryingOverURLLibRetry.__init__() missing 1 required positional argument: 'base_url'

Process finished with exit code 1
```

### Expected behavior

Return the project

### Python Version

3.1

### Toloka-Kit Version

1.2.2

### Other Packages Versions

anyio==4.4.0
attrs==23.2.0
cattrs==23.2.3
certifi==2024.6.2
charset-normalizer==3.3.2
docstring_parser==0.16
exceptiongroup==1.2.1
filelock==3.15.4
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
requests==2.32.3
simplejson==3.19.2
sniffio==1.3.1
tenacity==8.4.2
toloka-kit==1.2.2
tqdm==4.66.4
typing_extensions==4.12.2
urllib3==2.2.2

### Example code

```Python
cli = toloka.TolokaClient(token=TOLOKA_TOKEN, environment='PRODUCTION')
print(
    cli.get_project(xxx)
)
```

**Comment by saninstein** [comment]
Downgrade of the tenacity helps

`pip install -U tenacity==8.4.1`
